In [180]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/Fish.csv')
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [181]:
df['Species'].unique()
# 유니크 함수는 중복되지 않은 컬럼의 값들을 출력해줌

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [182]:
fish_input = df[['Weight', 'Length2', 'Length3', 'Height', 'Width']]
fish_input.head()

Weight  Length2  Length3   Height   Width
0   242.0     25.4     30.0  11.5200  4.0200
1   290.0     26.3     31.2  12.4800  4.3056
2   340.0     26.5     31.1  12.3778  4.6961
3   363.0     29.0     33.5  12.7300  4.4555
4   430.0     29.0     34.0  12.4440  5.1340

In [183]:
fish_target = df[['Species']]

In [184]:
# 트레이닝, 테스트로 데이터 분리
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = \
train_test_split(fish_input, fish_target)

In [185]:
# 각 데이터들간의 거리 수치가 다르기 때문에 스케일링 해줘야 함

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [186]:
type(test_scaled)

numpy.ndarray

In [187]:
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier()
kn.fit(train_scaled, train_target)

C:\Users\유승준\Desktop\DAMF2\ML\venv\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [188]:
print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

0.8571428571428571
0.8


In [189]:
test_scaled[:5]

array([[-0.8057995 , -0.70232558, -0.76718108, -0.73834565, -0.68796705],
       [-1.11075131, -1.49848414, -1.5600957 , -1.58902025, -1.96372903],
       [-0.1383466 , -0.15496658,  0.01661958,  0.77123083,  0.17547454],
       [-0.25700489,  0.59143207,  0.62725497, -0.78734619, -0.15911996],
       [-0.98378694, -1.32930045, -1.31401875, -0.52103281, -1.29795998]])

In [190]:
kn.predict(test_scaled)

array(['Roach', 'Smelt', 'Bream', 'Pike', 'Parkki', 'Pike', 'Bream',
       'Perch', 'Smelt', 'Bream', 'Whitefish', 'Pike', 'Perch', 'Perch',
       'Perch', 'Roach', 'Pike', 'Bream', 'Pike', 'Roach', 'Parkki',
       'Bream', 'Pike', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Bream', 'Bream', 'Smelt', 'Pike', 'Smelt', 'Bream', 'Perch',
       'Roach', 'Perch', 'Perch', 'Perch', 'Smelt'], dtype=object)

In [191]:
# 위의 예상치가 어떤 근거로 출력이 된 것인지 알 수 있는 함수
# 'Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'

kn.predict_proba(test_scaled)

# 7개의 클래스 중 하나일 확률
# 1열 기준 Whitefish일 확률 80%, Perch일 확률 20%

array([[0. , 0. , 0.4, 0. , 0.6, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. ],
       [0.8, 0.2, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0.6, 0. , 0. , 0. ],
       [0. , 0.4, 0.2, 0. , 0.4, 0. , 0. ],
       [0. , 0. , 0.2, 0.8, 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. ],
       [0.4, 0.2, 0. , 0. , 0. , 0. , 0.4],
       [0. , 0. , 0.2, 0. , 0.2, 0. , 0.6],
       [0. , 0. , 0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0.6, 0. , 0.4, 0. , 0. ],
       [0. , 0. , 0.6, 0. , 0.4, 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0. , 0.6, 0. , 0. ],
       [0. , 0. , 0.2, 0.8, 0. , 0. , 0. ],
       [0.4, 0.2, 0. , 0. , 0. , 0. , 0.4],
       [0. , 0. , 0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0.8, 0. , 0. ],
       [0. , 1. , 0. , 0. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. , 0. ,

In [192]:
distances, indexes = kn.kneighbors(test_scaled[3:4])
print(distances)
print(indexes)
# print(test_target)
# 판다스는 인덱스를 컬럼으로 인식, 넘파이는 인덱스를 정수로 인식하기 때문에

print(train_target.iloc[indexes[0]])
# 2차원 배열을 1차원으로 만들기 위해 iloc 사용
# test_scaled 4번째 값의 최근접을 뽑기 위한 것이기 때문에
# 근거는 train에 있음

[[0.20219347 0.58477748 0.65508092 0.90862145 1.02531343]]
[[ 10 103  41  14  28]]
    Species
130    Pike
133    Pike
128    Pike
108   Perch
107   Perch


## 로지스틱 회귀
- 결과값은 숫자로 나옴 = 회귀
- z 값이 높아지면 그 데이터일 확률이 높아진다 의 의미로 분류모델
- 시그모이드 함수 = 수식으로부터 나온 그래프라고 생각하면 됨
- 시그도모이드 함수에서 100%란 존재할 수 없다.
- z값이 많아져도 0이나 1이 될 수는 없다. 어떤 데이터를 쓰더라도 0과 1에 수렴한다.

### 5개의 특성을 통해 bream인지 smelt인지

In [193]:
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt') #~거나 ~거나
# bream이거나 smelt인 데이터를 모두 True로 바꿔줌

bream_smelt_indexes.head()

Species
55     False
36     False
73     False
141    False
26      True

In [194]:
train_bs = train_scaled[bream_smelt_indexes['Species']]
# # train_scaled에서 bream과 smelt 값(무게,길이 등)만 뽑아옴

# train_bs
train_scaled

array([[-0.34599861, -0.20472649, -0.20211549, -0.1628405 , -0.10340603],
       [-0.94225654, -0.98098108, -0.96768823, -0.88303393, -0.99004102],
       [-1.05201546, -1.42882026, -1.47807005, -1.29669943, -1.5014775 ],
       [ 2.56112959,  2.7808681 ,  2.62321247,  0.3759785 ,  1.59866703],
       [ 0.98890719,  0.69095189,  0.88244589,  1.70217098,  1.0422117 ],
       [ 1.67119238,  1.28807081,  1.42016959,  1.99699207,  1.21662864],
       [ 0.92957805,  0.49191225,  0.6910527 ,  1.36947204,  0.4872487 ],
       [-0.40532776, -0.05544676, -0.18388757, -0.41931638,  0.09470177],
       [-1.11075131, -1.57809999, -1.59655155, -1.63262302, -1.87804399],
       [-1.12944   , -1.95627531, -2.01579376, -1.62757575, -1.86908997],
       [-0.25700489,  0.69095189,  0.71839459, -0.73392929, -0.01834279],
       [-0.3608309 , -0.05544676, -0.18388757, -0.47334082, -0.04906007],
       [ 0.50240819,  0.64119198,  0.50877348,  0.27554726,  1.22719936],
       [-1.14694209, -0.75208549, -0.7

In [195]:
target_bs = train_target[bream_smelt_indexes['Species']]

# target_bs
train_target

Species
55   Whitefish
36       Roach
73       Perch
141       Pike
26       Bream
..         ...
20       Bream
37       Roach
91       Perch
59   Whitefish
64      Parkki

[119 rows x 1 columns]

In [196]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_bs, target_bs)

C:\Users\유승준\Desktop\DAMF2\ML\venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [197]:
print(lr.predict(train_bs[:5]))
print(lr.predict_proba(train_bs[:5]).round(3))
# train_bs까지가 array, .round를 통해 소숫점 뒤 세자리까지 출력

['Bream' 'Bream' 'Bream' 'Smelt' 'Bream']
[[0.997 0.003]
 [0.999 0.001]
 [0.993 0.007]
 [0.043 0.957]
 [0.999 0.001]]


In [198]:
lr.coef_ #코이피션트
# z = -0.5 x (Weight) + -0.6 x (Length) + ... 의 회귀 방정식을 만들어냄
# 생선을 판별하는 z 값을 구하는 방정식

array([[-0.4420577 , -0.60345398, -0.67409849, -0.9013855 , -0.72133264]])

In [199]:
lr = LogisticRegression(C=20, max_iter=1000)
# LogisticRegression() 안 넣어도 학습은 가능
# 사람이 직접 입력해야 하는 파라미터가 있음
# max_iter은 몇 번을 반복할까요? (기본값 = 100)
# C는 숫자가 커질수록 규제가 약해짐
lr.fit(train_scaled, train_target) # 7마리 생선이 다 들어가 있음

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.9411764705882353
0.975


C:\Users\유승준\Desktop\DAMF2\ML\venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [200]:
lr.predict_proba(test_scaled[:5]).round(3)
# 'Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt' 이 순서

array([[0.   , 0.02 , 0.601, 0.001, 0.347, 0.005, 0.026],
       [0.   , 0.002, 0.066, 0.   , 0.005, 0.928, 0.   ],
       [0.766, 0.152, 0.   , 0.   , 0.015, 0.   , 0.067],
       [0.   , 0.   , 0.127, 0.857, 0.015, 0.   , 0.   ],
       [0.   , 0.958, 0.001, 0.   , 0.034, 0.001, 0.005]])

In [201]:
# softmax 적용 전
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision, decimals=2))

[[ -4.84   0.43   3.85  -2.47   3.3   -0.97   0.7 ]
 [-11.13   1.29   4.92  -3.16   2.26   7.57  -1.74]
 [  6.96   5.34  -3.93  -4.13   3.01 -11.77   4.53]
 [ -4.84  -8.05   4.92   6.83   2.8   -0.97  -0.69]
 [ -2.86   6.21  -0.36  -6.45   2.86  -0.42   1.01]]


In [202]:
lr.coef_.shape
# coef 특성을 만들어 낼 때 사용
# 각 분류종에 대한 방정식을 각각 만들어냄 = 7개

# 로지스틱 함수는 각 z의 

(7, 5)

- 로지스틱회귀 = z값을 만들어주는 것
- 2진분류에서는 = 하나만 계산하고 나머지는 -하나
- 다중분류에서 로지스틱 회귀는 사용 X
- 왜? z1... zn개의 값이 나오고 각 z값의 확률을 계산하기 때문에 n개 클래스의 전체 확률을 계산했을 때, 합이 100%가 넘어감 (비율이 적용되지 않음)
- 따라서 이 경우 소프트맥스 = 데이터가 여러개일 때 